<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class ScheduleEvent extends Model
{
    protected $primaryKey = 'event_id';
    
    protected $fillable = [
        'title',
        'description',
        'event_date',
        'event_time',
        'event_type',
        'color',
        'is_active',
        'teacher_id',
        'class_id',
        'is_auto_generated',
        'shift_from',
        'shift_to',
    ];

    protected $casts = [
        'event_date' => 'date',
        'event_time' => 'datetime',
        'is_active' => 'boolean',
        'is_auto_generated' => 'boolean',
        'shift_from' => 'datetime', // Stored as time but cast as datetime for Carbon compatibility
        'shift_to' => 'datetime', // Stored as time but cast as datetime for Carbon compatibility
    ];

    public function scopeActive($query)
    {
        return $query->where('is_active', true);
    }

    public function scopeUpcoming($query)
    {
        return $query->where('event_date', '>=', now()->toDateString());
    }

    /**
     * Scope to filter by teacher
     * Returns events for the specific teacher OR global events (teacher_id = null)
     */
    public function scopeForTeacher($query, $teacherId)
    {
        if (!$teacherId) {
            // If no teacher ID provided, only return global events
            return $query->whereNull('teacher_id');
        }
        
        return $query->where(function($q) use ($teacherId) {
            $q->where('teacher_id', $teacherId)
              ->orWhereNull('teacher_id'); // Include global events
        });
    }

    /**
     * Scope to filter auto-generated events
     */
    public function scopeAutoGenerated($query)
    {
        return $query->where('is_auto_generated', true);
    }

    /**
     * Scope to filter manual events
     */
    public function scopeManual($query)
    {
        return $query->where('is_auto_generated', false);
    }

    /**
     * Get the teacher that owns this schedule event
     */
    public function teacher()
    {
        return $this->belongsTo(User::class, 'teacher_id', 'user_id');
    }

    /**
     * Get the class associated with this schedule event
     */
    public function studentClass()
    {
        return $this->belongsTo(StudentClass::class, 'class_id', 'class_id');
    }
}
